# Generated by Django 3.0 on 2019-12-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(to='imdb.Movie'),
        ),
    ]
